name: Flutter Web Build CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: subosito/flutter-action@master
    - run: flutter pub get
    - run: flutter channel beta
    - run: flutter upgrade
    - run: flutter config --enable-web
    - run: flutter create .
    - run: flutter build web
